Fix tut
nubcaker/CroCoMap pull request #12
Opened 2020-06-11 15:57 UTC by tieswesterborg

Fixed some typos in the tutorial
Added definition of a risky object

2020-06-11 18:27 UTC, nubcaker commented on src/components/pages/Tutorial.vue
> +                    <p>We define a high-risk object as an object that is touched by many different people (doorhandles, trash bins and park benches).</p>
Slightly different wording maybe: "We define a high-risk object as an object that bight be touched by many different people..."

2020-06-11 18:31 UTC, arbreurkes requested changes
Just the small changes please :)

2020-06-11 18:31 UTC, nubcaker commented on src/components/pages/Tutorial.vue
> +                    <p>You need to assesses whether an annotated object is high-risk and either select the best fitting snapshot or mark all object as `No Risk’. If you really don’t know, you should
typo: "assess", ", and", "the object"

2020-06-11 18:35 UTC, tieswesterborg commented on src/components/pages/Tutorial.vue
> +                    <p>You need to assesses whether an annotated object is high-risk and either select the best fitting snapshot or mark all object as `No Risk’. If you really don’t know, you should
Fixed :)

2020-06-12 07:57 UTC, arbreurkes requested changes
One typo :')

2020-06-12 07:57 UTC, nubcaker commented on src/components/pages/Tutorial.vue
> +                    <p>We define a high-risk object as an object that bight be touched by many different people (doorhandles, trash bins and park benches).</p>
Typo: "bight"

2020-06-12 08:51 UTC, arbreurkes approved these changes

2020-06-12 08:51 UTC, merged